config/routes.rb
Rails.application.routes.draw do
    get 'welcome/index'

    resources :persons
    root 'persons#index'
    get "/persons/new", to:"persons#new", as:"people"
    post "persons/new", to:"persons#create"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    get "api/index", to:"api#index", defaults:{format: "json"}
    get "api/show", to: "api#show", defaults:{format: "json"}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    validates :first_name, presence: true,
                    length: { minimum: 2 }
    validates :last_name, presence: true,
                    length: {minimum:2}
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

    def index
        @persons = Person.all
    end
    def show
        @person = Person.find(params[:id])
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
    def index
        @persons = Person.all
    end
    
    def show
        @person = Person.find(params[:id])
    end

    def  new
        @person = Person.new
    end

    def edit
        @person = Person.find(params[:id])
    end
    def create
        @person = Person.new(person_params)

        if @person.save
            format.html { redirect_to @person, notice: 'Person was successfully created.' }
       else
          render "new"
       end
    end

   def update
        @person = Person.find(params[:id])
       
     if @person.update(person_params)
        redirect_to @person
        else
          render 'edit'
        end
    end
    def destroy
        @person = Person.find(params[:id])
        @person.destroy
       
        redirect_to persons_path
      end
    
   private
        def person_params
            params.require(:person).permit(:first_name, :last_name, :email)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/_form.html.erb
<%= bootstrap_form_with(model: @person, local: true) do |form| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%#= form.label :firstName %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%#= form.label :lastName %><br>
    <%= form.text_field :last_name %>
  </p>

    <p>
    <%#= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
 <%= form.submit %>
<% end %>

app/views/persons/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="https://www.accenture.com/">Accenture</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', persons_path %></li>
      <li><%= link_to 'Add Person', new_person_path %></li>
    </ul>
  </div>
</nav>

app/views/persons/edit.html.erb
<head>
<%= render '/persons/header' %>
</head>

<h1>Edit Person</h1>
 <div class="container">
<%= render 'form' %>
 
<%= link_to 'Back', person_path %>
</div>

app/views/persons/index.html.erb
<%= render '/persons/header' %>
<body>

<div class="container">
<h1>People</h1>
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th></th>
  </tr>
 
  <% @persons.each do |person| %>
    <tr>
      <td><%= person.first_name %></td>
      <td><%= person.last_name %></td>
      <td><%= person.email %></td>

      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path([person]) %></td>
      <td><%= link_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Add Person', new_person_path %>
<div>

app/views/persons/new.html.erb
<head>
<%= render '/persons/header' %>
</head>

<div class="container">
<h1>Add new person</h1>
<%= render 'form' %>

<%= link_to 'Back', persons_path %>
</div>

app/views/persons/show.html.erb
<head>
<%= render '/persons/header' %>
</head>
<div class="container">
<h6>View Person<h6>
<p>
  <strong>First Name:</strong>
  <%= @person.first_name %>
</p>
 
<p>
  <strong>Last Name</strong>
  <%= @person.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>
<br>



<%= link_to 'Back', persons_path %>
<div>

app/views/welcome/index.html.erb
<h1>Hello Worlds</h1>
<p>Find me in app/views/welcome/index.html.erb</p>


<h1>Hello, Rails!</h1>
<%= link_to 'People', controller: 'persons' %>